In [12]:
import pandas as pd
from sklearn.tree import plot_tree
import matplotlib.pyplot as plt
import numpy as np
filename = 'C://train_r//data//data1_1//data1_1.csv'

data = pd.read_csv(filename)

In [13]:
data = data.fillna(0)
data = data.replace('Y', 1)
data.label.replace(['기타질병', '비브리오병', '연쇄구균병', '스쿠티카병', 
       '정상', '활주세균병', '에드워드병', 'VHSV'], [0, 1, 2, 3, 4, 5, 6, 7], inplace=True)

In [14]:
data

,label,OAA,OAB,OBA,OBB,OBC,OBD,OBE,OCA,OCB,...,IHA,IHB,IIA,IIB,IJA,IJB,수온(℃),전장(cm),중량(g),사육밀도(kg/m^2)
0,0,0,0,0,0,0,0,0,0,0.0,...,0,0.0,0,0.0,0.0,0.0,18.5,28.1,290,17
1,0,0,0,0,0,0,0,0,0,0.0,...,0,0.0,0,0.0,0.0,0.0,18.5,25.7,222,17
2,1,0,0,0,0,0,0,0,0,0.0,...,0,0.0,0,0.0,0.0,0.0,18.5,25.2,228,17
3,0,0,0,0,0,0,0,0,0,0.0,...,0,0.0,0,0.0,0.0,0.0,18.5,27.0,242,17
4,0,0,0,0,0,0,0,0,0,0.0,...,0,0.0,0,0.0,0.0,0.0,18.5,26.1,238,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
762,0,0,0,0,0,0,0,0,0,0.0,...,0,0.0,0,0.0,0.0,0.0,19.0,23.5,166,15
763,3,0,0,0,0,1,0,0,0,0.0,...,0,0.0,0,0.0,0.0,0.0,19.0,24.7,172,15
764,0,0,0,0,0,0,0,0,0,0.0,...,0,0.0,0,0.0,0.0,0.0,19.0,23.0,192,15
765,3,0,0,0,0,0,0,0,0,0.0,...,0,0.0,0,0.0,0.0,0.0,19.0,24.0,112,15
766,3,0,0,0,0,0,0,0,0,0.0,...,0,0.0,0,0.0,0.0,0.0,19.0,23.0,138,15

In [15]:
from pycaret.classification import *
setup_clf = setup(data=data, target='label')

In [16]:
rf = create_model('rf', fold=5)

In [17]:
top5 = compare_models(sort='Accuracy', n_select=5)

In [18]:
tuned_top5 = [tune_model(i) for i in top5]

In [19]:
blender_top5 = blend_models(estimator_list=tuned_top5)

In [20]:
final_model = finalize_model(blender_top5)
prediction = predict_model(final_model, data=data.iloc[-100:])

In [21]:
from pycaret.utils import check_metric
check_metric(prediction['label'], prediction['Label'], metric = 'Accuracy')

1.0